/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiGenerateReportRouteImport } from './routes/api/generate-report'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBeneficiariesRouteImport } from './routes/_app.beneficiaries'
import { Route as AppComplianceIndexRouteImport } from './routes/_app.compliance.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppComplianceVaultRouteImport } from './routes/_app.compliance.vault'
import { Route as AppComplianceScoreRouteImport } from './routes/_app.compliance.score'
import { Route as AppComplianceReportsRouteImport } from './routes/_app.compliance.reports'
import { Route as AppComplianceCalendarRouteImport } from './routes/_app.compliance.calendar'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateReportRoute = ApiGenerateReportRouteImport.update({
  id: '/api/generate-report',
  path: '/api/generate-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBeneficiariesRoute = AppBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceIndexRoute = AppComplianceIndexRouteImport.update({
  id: '/compliance/',
  path: '/compliance/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppComplianceVaultRoute = AppComplianceVaultRouteImport.update({
  id: '/compliance/vault',
  path: '/compliance/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceScoreRoute = AppComplianceScoreRouteImport.update({
  id: '/compliance/score',
  path: '/compliance/score',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceReportsRoute = AppComplianceReportsRouteImport.update({
  id: '/compliance/reports',
  path: '/compliance/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceCalendarRoute = AppComplianceCalendarRouteImport.update({
  id: '/compliance/calendar',
  path: '/compliance/calendar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/expenses': typeof AppExpensesRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/api/generate-report': typeof ApiGenerateReportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/compliance/calendar': typeof AppComplianceCalendarRoute
  '/compliance/reports': typeof AppComplianceReportsRoute
  '/compliance/score': typeof AppComplianceScoreRoute
  '/compliance/vault': typeof AppComplianceVaultRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/compliance/': typeof AppComplianceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/expenses': typeof AppExpensesRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/api/generate-report': typeof ApiGenerateReportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/compliance/calendar': typeof AppComplianceCalendarRoute
  '/compliance/reports': typeof AppComplianceReportsRoute
  '/compliance/score': typeof AppComplianceScoreRoute
  '/compliance/vault': typeof AppComplianceVaultRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/compliance': typeof AppComplianceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/beneficiaries': typeof AppBeneficiariesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/api/generate-report': typeof ApiGenerateReportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/compliance/calendar': typeof AppComplianceCalendarRoute
  '/_app/compliance/reports': typeof AppComplianceReportsRoute
  '/_app/compliance/score': typeof AppComplianceScoreRoute
  '/_app/compliance/vault': typeof AppComplianceVaultRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/compliance/': typeof AppComplianceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/beneficiaries'
    | '/dashboard'
    | '/documents'
    | '/expenses'
    | '/projects'
    | '/settings'
    | '/users'
    | '/whatsapp'
    | '/api/generate-report'
    | '/auth/callback'
    | '/compliance/calendar'
    | '/compliance/reports'
    | '/compliance/score'
    | '/compliance/vault'
    | '/projects/$id'
    | '/compliance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/beneficiaries'
    | '/dashboard'
    | '/documents'
    | '/expenses'
    | '/projects'
    | '/settings'
    | '/users'
    | '/whatsapp'
    | '/api/generate-report'
    | '/auth/callback'
    | '/compliance/calendar'
    | '/compliance/reports'
    | '/compliance/score'
    | '/compliance/vault'
    | '/projects/$id'
    | '/compliance'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/beneficiaries'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/expenses'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/whatsapp'
    | '/api/generate-report'
    | '/auth/callback'
    | '/_app/compliance/calendar'
    | '/_app/compliance/reports'
    | '/_app/compliance/score'
    | '/_app/compliance/vault'
    | '/_app/projects/$id'
    | '/_app/compliance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiGenerateReportRoute: typeof ApiGenerateReportRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-report': {
      id: '/api/generate-report'
      path: '/api/generate-report'
      fullPath: '/api/generate-report'
      preLoaderRoute: typeof ApiGenerateReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beneficiaries': {
      id: '/_app/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof AppBeneficiariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance/': {
      id: '/_app/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AppComplianceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/compliance/vault': {
      id: '/_app/compliance/vault'
      path: '/compliance/vault'
      fullPath: '/compliance/vault'
      preLoaderRoute: typeof AppComplianceVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance/score': {
      id: '/_app/compliance/score'
      path: '/compliance/score'
      fullPath: '/compliance/score'
      preLoaderRoute: typeof AppComplianceScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance/reports': {
      id: '/_app/compliance/reports'
      path: '/compliance/reports'
      fullPath: '/compliance/reports'
      preLoaderRoute: typeof AppComplianceReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance/calendar': {
      id: '/_app/compliance/calendar'
      path: '/compliance/calendar'
      fullPath: '/compliance/calendar'
      preLoaderRoute: typeof AppComplianceCalendarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppBeneficiariesRoute: typeof AppBeneficiariesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppComplianceCalendarRoute: typeof AppComplianceCalendarRoute
  AppComplianceReportsRoute: typeof AppComplianceReportsRoute
  AppComplianceScoreRoute: typeof AppComplianceScoreRoute
  AppComplianceVaultRoute: typeof AppComplianceVaultRoute
  AppComplianceIndexRoute: typeof AppComplianceIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBeneficiariesRoute: AppBeneficiariesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppComplianceCalendarRoute: AppComplianceCalendarRoute,
  AppComplianceReportsRoute: AppComplianceReportsRoute,
  AppComplianceScoreRoute: AppComplianceScoreRoute,
  AppComplianceVaultRoute: AppComplianceVaultRoute,
  AppComplianceIndexRoute: AppComplianceIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiGenerateReportRoute: ApiGenerateReportRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
